#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

# uniform dry column + prewetted ramp in the 10 bottom cells
cp 0/Sb.org 0/Sb
runApplication setFields

# also writes liquidBalance.csv (impesFoam fork, updateLiquidContent.H)
runApplication impesFoam

# Sb profile along the column at every write time
runApplication postProcess -func sampleDict
