#!/bin/sh
# BL_flow_BC, variant port: hybridPorousInterFoam_be54696
# Mesh and initial fields ship with the tutorial (tutorials/Darcy_Flow_Cases/Buckley-Leverett/flow_Driven_BrooksCorey).
cd "${0%/*}" || exit 1
. ../../../runTools.sh
runTmpLog log.hybridPorousInterFoam hybridPorousInterFoam_be54696
