#!/bin/sh
# BL_grav_BC, variant port: hybridPorousInterFoam_be54696
# Mesh and initial fields ship with the tutorial (tutorials/Darcy_Flow_Cases/Buckley-Leverett/gravity_Driven_BrooksCorey).
cd "${0%/*}" || exit 1
. ../../../runTools.sh
runTmpLog log.hybridPorousInterFoam hybridPorousInterFoam_be54696
