#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log.* liquidBalance.csv 0/alpha.wetting
foamListTimes -rm
rm -rf postProcessing dynamicCode constant/polyMesh
