#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

# uniform dry column + prewetted ramp in the 10 bottom cells
cp 0/alpha.wetting.orig 0/alpha.wetting
runApplication setFields

# also writes liquidBalance.csv (coded function object in system/controlDict)
runApplication hybridPorousInterFoam

# alpha profile along the column at every write time (same sampleDict as
# ../1D_vertical_impes_inletRes)
runApplication postProcess -func sampleDict
