#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/polyMesh/boundary > /dev/null 2>&1
cleanCase

rm log0* > /dev/null 2>&1
rm log1* > /dev/null 2>&1
rm Results* > /dev/null 2>&1
rm tau.dat > /dev/null 2>&1

if [ -d "0.bkp" ]; then
    rm -rf 0/ > /dev/null 2>&1
    mv 0.bkp/ 0/ > /dev/null 2>&1
fi