#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

N=4

# Clean case
./AllClean

#Creation cartesian mesh for REV
blockMesh   > log0a.blockMesh

echo "Running snappyHexMesh on $PWD"
snappyHexMesh -overwrite > log0b.snappyHexMesh

# Scale the geometry. Usually scaling factor is equal to average grain size
transformPoints "scale=(1e-2 1e-2 1e-2)" > log0c.scale

# Check mesh. Useful for quality check and subsequent post-processing
checkMesh > log0d.checkMesh

# Overwrite all regions created by snappyHexMesh keeping only region0 which is the main one
# Check log0c.checkMesh and control that other regions are made by few cells
if [ -f "constant/polyMesh/sets/region0" ]; then
    subsetMesh region0 -overwrite > log0e.subsetMesh

    # Check mesh after subsetMesh. Useful for quality check and subsequent post-processing
    checkMesh > log0f.checkMesh_post
fi