#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../runTools.sh

# case 2 - with gravity

runApplication blockMesh
runApplication topoSet
cp 0/Sb.org 0/Sb
runApplication setFields
# solver log written in /tmp during the run (see ../runTools.sh);
# LOG_EVERY=N ./run keeps only every Nth time step of it
echo "Running impesFoam on $PWD"
runTmpLog log.impesFoam impesFoam
runApplication postProcess -func sampleDict
